"use client";

import { useEffect, useRef, useState } from "react";
import client from "../api/client";
import Modal from "../components/Modal";
import AuditPanel from "../components/AuditPanel";
import { useAuth } from "../context/AuthContext";

const stageLabels = { JEPending: "JE तपासणीसाठी प्रलंबित", OSPending: "OS तपासणीसाठी प्रलंबित", PaymentRequired: "पेमेंट लिंक पाठवली", PaymentVerificationPending: "पेमेंट पडताळणी प्रलंबित", AssistantCommissionerApprovalPending: "सहाय्यक आयुक्त मंजुरीसाठी प्रलंबित", Approved: "मंजूर", Rejected: "नाकारले" };
const stageLabel = (stage) => stageLabels[stage] || stage || "-";
const paymentStatusLabel = (status) => ({ PaymentRequired: "Payment Pending", PaymentPending: "Payment Pending", PaymentVerificationPending: "Payment Done", PaymentVerified: "Payment Done", PaymentDone: "Payment Done" })[status] || status || "-";

function EyeIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" strokeWidth="2"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z" /><circle cx="12" cy="12" r="2.5" /></svg>; }

export default function DemandOfficerPage() {
  const { user } = useAuth();
  const [items, setItems] = useState([]); const [message, setMessage] = useState(""); const [processingId, setProcessingId] = useState(null); const [selected, setSelected] = useState(null); const [decisions, setDecisions] = useState({}); const actionInFlight = useRef(false);
  const load = async (quiet = false) => { try { const response = await client.get("/demand-workflow/queue"); setItems(response.data.data || []); if (!quiet) setMessage(""); } catch (error) { if (!quiet) setMessage(error.response?.data?.messageMr || "अधिकारी अर्ज लोड करता आले नाहीत."); } };
  useEffect(() => { load(); const timer = window.setInterval(() => load(true), 20000); return () => window.clearInterval(timer); }, []);
  const setDecision = (id, values) => setDecisions((current) => ({ ...current, [id]: { ...current[id], ...values } }));
  const runAction = async (item, endpoint, body, successMessage) => {
    if (actionInFlight.current) return;
    actionInFlight.current = true; setProcessingId(item.id); setMessage("");
    try { await client.post(`/demand-workflow/${item.demandApplicationId}/${endpoint}`, body); setDecisions((current) => { const next = { ...current }; delete next[item.id]; return next; }); await load(true); setMessage(successMessage); }
    catch (error) { setMessage(error.response?.data?.messageMr || error.response?.data?.message || "कार्यवाही करता आली नाही. कृपया पुन्हा प्रयत्न करा."); }
    finally { setProcessingId(null); actionInFlight.current = false; }
  };
  const submitDecision = (item) => {
    const decision = decisions[item.id] || {}; const finalApproval = item.stage === "AssistantCommissionerApprovalPending"; const approve = finalApproval ? decision.choice === "approve" : decision.choice === "accept";
    if (!decision.choice) return setMessage(finalApproval ? "कृपया मंजुरी निवडा." : "कृपया स्वीकार किंवा नकार निवडा.");
    if (!approve && !decision.reason?.trim()) return setMessage("नकारासाठी कारण / शेरा आवश्यक आहे.");
    const paymentRequest = item.stage === "OSPending" && approve; const amount = Number(String(decision.amount ?? "").trim());
    if (paymentRequest && (!Number.isFinite(amount) || amount <= 0)) return setMessage("कृपया वैध शुल्क रक्कम प्रविष्ट करा.");
    const endpoint = paymentRequest ? "payment-request" : item.stage === "JEPending" ? "je" : item.stage === "OSPending" ? "os" : finalApproval ? "approve" : "payment/verify";
    return runAction(item, endpoint, paymentRequest ? { payableAmount: amount } : finalApproval ? {} : { approve, reason: decision.reason?.trim() || undefined }, paymentRequest ? "पेमेंट लिंक अर्जदाराला पाठवली आहे." : approve ? "अर्जावरील कार्यवाही यशस्वी झाली आहे." : "अर्ज नाकारला आहे.");
  };
  const openDetails = async (item) => { try { const response = await client.get(`/demand-applications/${item.demandApplicationId}`); setSelected({ workflow: item, application: response.data.data }); } catch { setMessage("अर्जाची माहिती लोड करता आली नाही."); } };
  const title = user?.role === "JE" ? "अधिकारी मागणी अर्ज — JE" : user?.role === "OS" ? "अधिकारी मागणी अर्ज — OS" : "सहाय्यक आयुक्त — मागणी अर्ज";
  const paymentControl = (item, processing) => { const current = ["PaymentDone", "PaymentVerified", "PaymentVerificationPending"].includes(item.paymentStatus) ? "PaymentDone" : "PaymentPending"; return <><span style={{ fontSize: 12, fontWeight: 600, color: "#475569" }}>Payment Status: {paymentStatusLabel(item.paymentStatus)}</span><label style={{ display: "inline-flex", gap: 6, fontSize: 13 }}><input type="checkbox" checked={current === "PaymentPending"} disabled={processing} onChange={() => runAction(item, "payment-status", { status: "PaymentPending" }, "Payment Pending जतन केले आहे.")} /> Payment Pending</label><label style={{ display: "inline-flex", gap: 6, fontSize: 13 }}><input type="checkbox" checked={current === "PaymentDone"} disabled={processing} onChange={() => runAction(item, "payment-status", { status: "PaymentDone" }, "Payment Done जतन केले आहे.")} /> Payment Done</label>{current === "PaymentDone" && <button className="btn btn-primary btn-sm" disabled={processing} onClick={() => runAction(item, "forward-to-assistant-commissioner", {}, "अर्ज सहाय्यक आयुक्तांकडे पाठवला आहे.")}>{processing ? "पाठवत आहे..." : "सहाय्यक आयुक्तांकडे पाठवा"}</button>}</>; };
  const decisionControl = (item) => {
    const decision = decisions[item.id] || {}; const processing = processingId === item.id; const paymentStage = user?.role === "OS" && ["PaymentRequired", "PaymentVerificationPending"].includes(item.stage);
    if (paymentStage) return <div style={{ minWidth: 214, display: "grid", gap: 6 }}><button type="button" className="btn btn-outline btn-sm" onClick={() => openDetails(item)}><EyeIcon /> View</button>{paymentControl(item, processing)}</div>;
    const finalApproval = item.stage === "AssistantCommissionerApprovalPending";
    return <div style={{ minWidth: 214, display: "grid", gap: 6 }}><button type="button" className="btn btn-outline btn-sm" onClick={() => openDetails(item)}><EyeIcon /> View</button><span style={{ fontSize: 12, fontWeight: 600 }}>निर्णय:</span>{finalApproval ? <label><input type="radio" name={`decision-${item.id}`} checked={decision.choice === "approve"} onChange={() => setDecision(item.id, { choice: "approve" })} disabled={processing} /> मंजूर</label> : <><label><input type="checkbox" checked={decision.choice === "accept"} onChange={(e) => setDecision(item.id, { choice: e.target.checked ? "accept" : "" })} disabled={processing} /> Accept</label><label><input type="checkbox" checked={decision.choice === "reject"} onChange={(e) => setDecision(item.id, { choice: e.target.checked ? "reject" : "" })} disabled={processing} /> Reject</label>{item.stage === "OSPending" && decision.choice === "accept" && <label style={{ display: "grid", gap: 4, fontSize: 12 }}>शुल्क रक्कम <span>₹<input className="form-input" type="number" min="0.01" step="0.01" style={{ minHeight: 34, width: 142 }} value={decision.amount || ""} onChange={(e) => setDecision(item.id, { amount: e.target.value })} disabled={processing} /></span></label>}{decision.choice === "reject" && <input className="form-input" placeholder="नकाराचे कारण / शेरा *" value={decision.reason || ""} onChange={(e) => setDecision(item.id, { reason: e.target.value })} disabled={processing} />}</>}<button className="btn btn-primary btn-sm" disabled={processing || !decision.choice || (item.stage === "OSPending" && decision.choice === "accept" && !String(decision.amount ?? "").trim())} onClick={() => submitDecision(item)}>{processing ? "सादर करत आहे..." : item.stage === "OSPending" && decision.choice === "accept" ? "Send Payment Request to Applicant" : "Submit"}</button></div>;
  };
  const showArea = user?.role === "OS";
  return <div><div className="page-header"><div><div className="page-title">{title}</div><div className="page-subtitle">अर्ज पडताळणी व कार्यवाही</div></div><button className="btn btn-outline" onClick={() => load()}>Refresh</button></div>{message && <div className="error-msg" role="status">{message}</div>}{items.length > 0 ? <><h2>प्रलंबित अर्ज: {items.length}</h2><div className="card" style={{ padding: 16, overflowX: "auto" }}><table><thead><tr><th>अर्ज क्रमांक</th><th>अर्जदार</th><th>सेवा</th>{showArea && <th>क्षेत्रफळ</th>}<th>शुल्क</th><th>स्थिती</th><th>Payment Status</th><th>कार्यवाही</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.applicationNumber}</td><td><b>{item.applicantName || "-"}</b><br /><small>{item.mobile || ""}</small></td><td>{item.serviceDescription || "-"}</td>{showArea && <td>{item.spaceRequirement || "-"}</td>}<td>₹{Number(item.payableAmount || 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })}</td><td>{stageLabel(item.stage)}</td><td>{paymentStatusLabel(item.paymentStatus)}</td><td>{decisionControl(item)}</td></tr>)}</tbody></table></div></> : !message && <div className="card empty-state">कोणताही अर्ज प्रलंबित नाही.</div>}{selected && <Modal title={`अर्ज तपशील — ${selected.application.applicationNumber}`} onClose={() => setSelected(null)} footer={<button className="btn btn-primary" onClick={() => setSelected(null)}>ठीक आहे</button>}><div className="property-info-grid"><span>अर्जदार: <b>{selected.application.applicantName}</b></span><span>मोबाईल: <b>{selected.application.mobile}</b></span><span>ई-मेल: <b>{selected.application.email || "-"}</b></span><span>स्थिती: <b>{stageLabel(selected.workflow.stage)}</b></span><span>देयक स्थिती: <b>{paymentStatusLabel(selected.workflow.paymentStatus)}</b></span><span>शुल्क: <b>₹{selected.workflow.payableAmount || 0}</b></span></div><h3 style={{ margin: "18px 0 6px" }}>कार्यवाही इतिहास</h3><AuditPanel entityName="DemandApplication" entityId={selected.application.id} /></Modal>}</div>;
}
